library(tidyverse)
library(dplyr)
library(ggthemes)



## Incarceration

#### Name: Ahshah Kennedy
#### Date: 5/30/2024


#### Introduction
```{r}
###  Mass incarceration in the United States is a major issue that affects millions of families everyday. The United States has the more inmates in prison and jail than any other country and it is no secret that Black people are the most impacted. The United States historically has used prison systems to control and silence community leaders and populations who do not fit into the boxes that were put upon them. To look into this matter further, I will be using a Vera Institute dataset that records prison and jail population rates per 100,000 people from 1990-2016. By looking upon this dataset I will analyze data from U.S and King County, here in Washington State, looking at the rates of Black people incarcerated in a 4 year span, along with the comparison of Black and Native jail population rates in a 4 year span. By looking at the variables I want to show how prominent this matter is and bring upon questions that contribute to answering why Mass Incarceration is a major issue. 
```



#### 5 values calculated from the data include
```{r}
#### Through my analyzation of incarceration data 5 values I captured are, values of race, geographic location, gender, difference of incarcertion rates in years and difference of incarceration rates for those in jail and those in prison. 
```

#### About the dataset
```{r}
#### The dataset this report is based on is from Vera Institute which records prison and jail population rates per 100,000 people from 1990-2016 . This data set looks at the different states and counties across the U.S , calculating male and female jail/prison rates, in addition to the amount of those incarcerated based on their race. Races include Black, White, Latinx, Asian/Islander, Native and lastly White. The data set also accounts for geographic location. Vera, who is providing the data, is an organization commited to ending Mass Incarceration and recognizes it as a nation wide issue, as it's increasingly not because just an urban story. Smaller communities outside urban limits are increasingly facing the impact of mass incarceration and the racial disparities continue to rise. Vera holds the U.S government accountable and recognizes the funds U.S takes from American tax dollars to build more prison and jail systems. Imagine if this money was put into building more schools and upgrading the ones we already have. Limitations of this data include frequent NA values in rural areas that may also be overwhelmingly white. This is a problem because it would be helpful for anyone analyzing to be able to compare these values of race and incarceration populations to areas that are more diverse in race like smaller, mid city, urban areas.
```

```{r}
incarceration_us <- read.csv("https://raw.githubusercontent.com/melaniewalsh/Neat-Datasets/main/us-prison-jail-rates-1990.csv")
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
black_pop_yearly <- incarceration_us %>%
  group_by(year) %>%
  summarize(black_prison_pop_rate = mean(black_prison_pop_rate, na.rm = TRUE))

years_highlight <- black_pop_yearly %>%
  filter(year %in% c(2013,2014,2015,2016))

ggplot(years_highlight, aes(x= year, y= black_prison_pop_rate)) +
  geom_line(color ="blue") +
  geom_point(data = years_highlight, aes(x = year, y = black_prison_pop_rate), color = "red", size = 3) +
  #scale_x_continuous(breaks= c(2013, 2014, 2015, 2016)) +
  labs(title = paste("Black Prison Population rate in a 4 year span"),
       x= "Year",
       y= "Black population rate",
       caption = "Source: https://raw.githubusercontent.com/melaniewalsh/Neat-Datasets/main/us-prison-jail-rates-1990.csv"
         ) +
  theme_minimal()
```

#### About the chart above

```{r}
"In the chart above, I wanted to diplayt he trends seen in the data regarding Black prison population rates from the msot recent years in the set, 2013-2016. This chart is telling of multiple things one being the extremely high rates in the year of 2013 along with this rate massively declining in 2016. Why was this rate so high in 2013? And why such the decline in 2016 as that was the year Barack Obama left office. I chose to focus on the black rate because once again it was the highest, and not enough legislation is being passed to stop the mass incarceration of Black people in the United States. Many liek to think its because they are dooing more crime but it's evident and important to take into account the racial context of prisons in the first place along with the prevalnce of Balck people being stop and frisked, targeted and tormented by the justice system in itself. These data rates account for across all the 51 states in America. "

```

```{r}

county_name <- "King County"

county_data <- incarceration_us %>%
  filter(county_name == "King County", state == "WA")
  
  black_jail_year <- county_data %>%
  group_by(year) %>%
  summarize(black_jail_pop_rate = mean(black_jail_pop_rate, na.rm = TRUE))
  
  native_jail_year <- county_data %>%
    group_by(year) %>%
    summarize(native_jail_pop_rate = mean(native_jail_pop_rate, na.rm = TRUE))

combined_rates <- black_jail_year %>%
  inner_join(native_jail_year, black_jail_pop_rate, by = "year") 

highlight_years <- combined_rates %>%
  filter(year %in% c(2013,2014,2015,2016))
```

```{r}

ggplot() +
  geom_line(data = highlight_years, aes(x = year, y = black_jail_pop_rate, color ="blue")) +
  geom_point(data = highlight_years, aes(x = year, y = black_jail_pop_rate, color = "pink"), size = 3) +
  geom_line(data = highlight_years, aes(x = year, y = native_jail_pop_rate, color = "pink")) +
  geom_point(data = highlight_years, aes(x = year, y = native_jail_pop_rate, color = "blue"), size = 3) +
  labs(title = paste("Black and Native Jail Population rates in", county_name, "Over a 4 year span"),

x= "Year",
y= "Jail Population rate",

caption = "Source: https://raw.githubusercontent.com/melaniewalsh/Neat-Datasets/main/us-prison-jail-rates-1990.csv"

  ) +
  theme_minimal()
```



#### About the chart above

```{r}

"This trends comparison chart shows the Black and Native jail population rates per 100,000 people in King County from the years 2013-2016. The pink line symbolizes the black jail rate, while the blue line symbolizes the native rates. I chose to focus on Black and Native jail rates because these the youth the face the highest incarceration rates compared to other groups in this data set. With these rates so high with Black youth being massive numbers, it goes to show has these two groups who have been historically oppressed fill U.S jails the most. Given that this is for juveniles, we can begin to to think as to what factors contribute to this, beyond oppression it shows the lack of resources in these communties, education limitations, environmental disruptors and prejudice from police. It known that youth are a product of their environment and it's important that they are given tools to be successful. With incarceration numbers for youth being so high for Natives and Black its telling that there is a problem with our governmental system, especially in terms of the results of historically oppression that they fail to confront continously. Although we see a step decline for Natives approaching 2016, the rate is still way above compared to other group and the same could be said for Black people. Hopefully this chart is insightful and helps you visualize and remian curious about this issue. "

```



  
       
       
       
 
 
 

  




